name: Setup
description: "Setup the environment"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "20"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - name: Install dependencies
      run: npm ci
