services:
  bank:
    build:
      context: ./bank
    ports:
      - "3000:3000"
    volumes:
      - .bank:/app
      - /app/node_modules
    env_file:
      - ./bank/.env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 5s

  atm:
    build:
      context: ./atm
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

