services:
  bank:
    build:
      context: ./bank
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./bank/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 5s

  atm:
    build:
      context: ./atm
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./atm/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

